### PR TITLE
Update admins.md - Add Madison

### PR DESCRIPTION
**Pull request by mix3d**

### CODE REVIEW

**Review by matthewrose — APPROVED** [review]

**Review by sholsinger — CHANGES_REQUESTED** [review]
@mix3d If you don't mind adding a blank line to the end of the file so that future additions are a bit cleaner, that'd be appreciated. :)

**Comment by mix3d** [comment]
@sholsinger what's weird is that on my branch it DOES blank line on L48... weird.

Going to checkout locally and commit. Maybe it's a Github editor problem.

**Comment by mix3d** [comment]
@sholsinger I've checked it out locally too, there IS an extra line that doesn't seem to be showing in the diff... even when expanded.

image

**Review by sholsinger — APPROVED** [review]
🚀 LGTM

**Pull request merged**
